# Autogenerated wrapper script for Hanabi_jll for i686-w64-mingw32-cxx11
export compile_commands, libhanabi, libhanabi_h

JLLWrappers.@generate_wrapper_header("Hanabi")
JLLWrappers.@declare_file_product(compile_commands)
JLLWrappers.@declare_library_product(libhanabi, "libhanabi.dll")
JLLWrappers.@declare_file_product(libhanabi_h)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        compile_commands,
        "share\\compile_commands.json",
    )

    JLLWrappers.@init_library_product(
        libhanabi,
        "bin\\libhanabi.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        libhanabi_h,
        "include\\pyhanabi.h",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
